version: '3.8'
services:
  virtu_care_postgres:
    container_name: virtu_care_postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${VIRTU_CARE_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${VIRTU_CARE_POSTGRES_PASSWD:-hunter2}
      POSTGRES_DB: ${VIRTU_CARE_POSTGRES_DB:-virtu_care}
    ports:
      - ${VIRTU_CARE_POSTGRES_PORT:-5432}:5432
    volumes:
      - virtu_care_data:/var/lib/postgresql/data
  virtu_care_rabbitmq:
      container_name: virtu_care_rabbitmq
      image: rabbitmq:3.12.6-management-alpine
      restart: always
      environment:
        RABBITMQ_DEFAULT_USER: ${VIRTU_CARE_RABBITMQ_USER:-user}
        RABBITMQ_DEFAULT_PASS: ${VIRTU_CARE_RABBITMQ_PASS:-hunter2}
      ports:
        - ${VIRTU_CARE_RABBITMQ_PORT:-5672}:5672
      volumes:
        - virtu_care_rabbitmq_data:/var/lib/rabbitmq/data
volumes:
  virtu_care_data: ~
  virtu_care_rabbitmq_data: ~
networks:
  example-net:
    driver: bridge